version: "3"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - .requirements/nginx//conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always